### ISSUE TITLE
Languagetool: API doesn't accept query.  Error: langCode cannot be empty or whitespace only

### ISSUE THREAD

**Issue by ttxtea** [wysiib/linter-languagetool#39]
I get the following error message with linter-languagetool 0.11.0 and atom 1.57.0:

~~~
Languagetool: API doesn't accept query.

Error: langCode cannot be empty or whitespace only
~~~

**Comment by wysiib** [comment]
Please use the preferences to provide an appropriate language code (e.g., de-DE for German) for the plugin to use. There should probably be a sensible default to it, but for now you would need to set it manually.

**Comment by ttxtea** [comment]
Ah thanks. I set `Mother Tongue` and `Preferred Variants` first to `en-US` and then to `de-DE` with lists it complains. But now I don't see `linter-languagetool` in the menu anymore. But it does say `LT` with an blue curly underline in the lower tray in ATOM. It almost looks as if LT is spelled wrong :-)

**Comment by ttxtea** [comment]
With an other document some error message about a too long text popped up, but to quickly for me to read it.

**Comment by ttxtea** [comment]
OK - now I closed a lot of tabs in ATOM and it seems to work very smoothly!

**Comment by wysiib** [comment]
For the too long text, you might have run into #32. The public API does not support arbitrary sizes. You could use a local installation of language tool to overcome this limitation.

Other than that, great to hear that you got everything running. The plugin is not supported much these days, since I do not use Atom anymore. However, I try to keep it functional as far as possible for now.
